# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_Amount', models.IntegerField()),
                ('director_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_id', models.CharField(max_length=255)),
                ('director_Name', models.CharField(max_length=255)),
                ('director_Bio', models.CharField(max_length=555)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField()),
                ('genre_Type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('payment_Amount', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('plan_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_Name', models.CharField(max_length=255)),
                ('plan_id', models.IntegerField()),
                ('user_Name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('user_email', models.CharField(max_length=255)),
                ('user_Contactnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('user_Name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.IntegerField()),
                ('show_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_Name', models.CharField(max_length=255)),
                ('show_id', models.IntegerField()),
                ('ratings', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('reviews_id', models.CharField(max_length=255)),
                ('director_id', models.CharField(max_length=255)),
                ('director_Name', models.CharField(max_length=255)),
                ('budget_Amount', models.IntegerField()),
                ('genre_id', models.IntegerField()),
                ('genre_Type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_Name', models.CharField(max_length=255)),
                ('user_Age', models.IntegerField()),
                ('user_email', models.CharField(max_length=255)),
                ('user_Contactnumber', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
